### ISSUE TITLE
Navigator shortcuts create empty task

### ISSUE THREAD

**Issue by frankrousseau** [jsilvestre/tasky#11]
I like to use ctrl+pageup, ctrl+pagedown, ctrl+w to navigate between tabs or close them. When I'm in tasky, it detects a key movement and create a new empty task. That doesn't harm my data but it is not very pleasant to have to clean tasks on a regular basis.

**Comment by frankrousseau** [comment]
The problem looked solved but I noticed undefined task in my todo list. If I have a way to reproduce I will tell you.

**Comment by jsilvestre** [comment]
Ok, feel free to open a new issue if you meet this bug. @bnjbvr do you still encounter your bug?

**Comment by bnjbvr** [comment]
Yes, same bug (pasting something in the input field erases the previous content, as described in my last comment). Sorry I can't test right now with another platform than linux, will try under MacOS soonish.

**Comment by jsilvestre** [comment]
@bnjbvr is the bug still present in the latest version?

**Comment by bnjbvr** [comment]
Nope, it looks fixed on my side. Good work, komrad!
