### ISSUE TITLE
Do not take into account done tasks

### ISSUE THREAD

**Issue by Kloadut** [jsilvestre/tasky#22]
The number of tasks "To be done" includes the "Done" tasks.

![capture du 2014-12-17 12 09 59](https://cloud.githubusercontent.com/assets/1279740/5470381/4698c38c-85e7-11e4-8486-321a6ae0300f.png)

Keeping them stroked into the list is great, but we should avoid taking them into account.

**Comment by jsilvestre** [comment]
Closing for now since nobody complained about it!
