### ISSUE TITLE
Tasky is no more mobile friendly

### ISSUE THREAD

**Issue by Kloadut** [jsilvestre/tasky#30]
Hi jailvestre !
There is a bit too much padding for a mobile view:

![capture du 2014-12-24 19 38 06](https://cloud.githubusercontent.com/assets/1279740/5550132/a26c26d0-8b9c-11e4-8967-dcf689f1a765.png)

PS: Is there a way to see the dynamic tag-tree as in the desktop view ?

**Comment by jsilvestre** [comment]
Menu button is broken.

**Comment by jsilvestre** [comment]
The didn't publish a new version, but a new build is available and it fixes the menu on small screens. It's still not easy to use, but at least there is something. Let me know if it's okay with you so I close the issue.
