### ISSUE TITLE
Problem when all tasks are done

### ISSUE THREAD

**Issue by poupotte** [jsilvestre/tasky#34]
When all tasks are done, I think count should be (0/x) instead of (x).

![tasky](https://cloud.githubusercontent.com/assets/2659119/6040507/e98df128-ac72-11e4-92da-b5dcbb066f6c.png)

**Comment by jsilvestre** [comment]
Just noticed you reports...sorry for not getting to it earlier.

This is the intended behaviour, but I had no idea on what to do here. I'm going to change it so it works as you think it should, it makes more sense.

**Comment by jsilvestre** [comment]
This change is in the last version. Let me know if you think it's better like this, or if you have any idea to improve this.
