### ISSUE TITLE
Missing localization for favorite button title

### ISSUE THREAD

**Issue by nicofrand** [jsilvestre/tasky#37]
It seems that the (french) localization is missing for the favorite button title :

![tasky-missing-l10n](https://cloud.githubusercontent.com/assets/3419050/8956282/855c247a-35f4-11e5-9fa8-6346c7dab171.png)

**Comment by jsilvestre** [comment]
Thank you for the report, I'm going to fix it!

**Comment by jsilvestre** [comment]
It's been fixed in the rework, but it won't be link to a specific commit.
