### ISSUE TITLE
Cannot delete task on Firefox mobile

### ISSUE THREAD

**Issue by nicofrand** [jsilvestre/tasky#38]
Using Firefox mobile for Android, I cannot delete a task like on desktop by pressing the backspace key.

**Comment by jsilvestre** [comment]
Thank you for the report, I will look into it!

**Comment by nicofrand** [comment]
Still present.

**Comment by jsilvestre** [comment]
Apparently it's a bug in Firefox Mobile: https://bugzilla.mozilla.org/show_bug.cgi?id=737658
