### ISSUE TITLE
Tags can't be followed by a comma

### ISSUE THREAD

**Issue by jsilvestre** [jsilvestre/tasky#41]
As reported on the forum, in the task "#tag1, #tag2", "#tag1" is not considered as a tag.

See: https://forum.cozy.io/t/tasky-detecter-tags-separes-par-une-virgule/1229

**Comment by nicofrand** [comment]
What about ":" ?

Ex: "#task: something to do"

**Comment by jsilvestre** [comment]
What do you mean?

**Comment by nicofrand** [comment]
In MY case, I'd like "task" to be detected too in "#task: something to do" and "#task1; #task2"

**Comment by jsilvestre** [comment]
You are right, let's do that too. Thanks!

**Comment by nicofrand** [comment]
Fixed for me !

**Comment by nicofrand** [comment]
Fixed for me

**Comment by jsilvestre** [comment]
Great, thanks!
