### ISSUE TITLE
Private browsing cause application crash at startup

### ISSUE THREAD

**Issue by jsilvestre** [jsilvestre/tasky#42]
When browsing privately,
```
_favoriteSearch = JSON.parse(json)
```
Cause the code to crash, json is undefined.

**Comment by nicofrand** [comment]
*json* is equal to localStore.getItem("tasky.favorite_search").
The "tasky.favorite_search" entry was correctly in my localStorage but the value was "undefined".

**Comment by jsilvestre** [comment]
This should be fixed with the reworked code. I don't close, I will need your validation first!

**Comment by nicofrand** [comment]
Seems OK now !

**Comment by jsilvestre** [comment]
Great, let me know if something goes wrong again.
