### ISSUE TITLE
Adding a tag to an untagged task does not remove it from "without tag"

### ISSUE THREAD

**Issue by nicofrand** [jsilvestre/tasky#43]
Steps to reproduce:

* Create a task "test"
* Click on "Without tag"
* Rename your "test" task into "#test"

What I expect:
* A new tag is created (if necessary) with a task named "#test" inside
* The old task is removed from "Without tag"

What happens:
* The new tag is created with "#test" inside
* A blank task still appears in "Without tag"

**Comment by jsilvestre** [comment]
Thank you for the report, I'm moving forward with Tasky so hopefully it won't stay unfixed!

**Comment by jsilvestre** [comment]
I  tried to reproduce with the new reworked version, and I didn't manage to reproduce. I will let you try again when the said version is released to confirm.

**Comment by nicofrand** [comment]
Thanks !

**Comment by nicofrand** [comment]
Fixed
