### ISSUE TITLE
Tags with "-" do not work anymore

### ISSUE THREAD

**Issue by nicofrand** [jsilvestre/tasky#45]
**Steps to reproduce**

0. Create a task "#tag-with-hyphen"
0. Click in the menu on the new tag "tag-with-hyphen"

**What happens**

All the tasks are displayed

**What I expect**

Only the tasks with "#tag-with-hyphen" should be displayed

**Comment by jsilvestre** [comment]
Right, I see exactly what is wrong. Thanks for the report, I'm going to fix it ASAP!

**Comment by nicofrand** [comment]
The second regex would cover most of the case indeed (at least I do not find any normal case not covered yet) !

**Comment by jsilvestre** [comment]
I have published a new version with a fix. Let me know if it works for you!

**Comment by nicofrand** [comment]
It works, thanks
